name: Bioconda backups

on:
  schedule:
  - cron: "0 23 * * * "

jobs:

  build:
 
    runs-on: self-hosted
    steps:
    - name: Backup bioconda containers to local and aws registries
      run: |
        cd /home/debian/sync && node index.js --backup --aws --conda --updated